# Generated by Django 5.0.7 on 2024-08-02 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.AddField(
            model_name='contact',
            name='choosefile',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
