# Generated by Django 5.0.7 on 2024-08-03 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='uploaded_at',
        ),
    ]
