# Generated by Django 5.0.7 on 2024-08-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_remove_galleryimage_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.CharField(),
        ),
    ]
