# Generated by Django 5.0.7 on 2024-08-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
