# Generated by Django 5.0.7 on 2024-08-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_alter_event_description_delete_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster',
            field=models.ImageField(default=0, upload_to='event/'),
            preserve_default=False,
        ),
    ]
