# Generated by Django 5.0.7 on 2024-08-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_event_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='story/')),
                ('content', models.TextField()),
                ('creator', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'story_table',
            },
        ),
    ]
