# Generated by Django 5.0.7 on 2024-08-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
