# Generated by Django 5.0.7 on 2024-08-06 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0015_update'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Update',
        ),
    ]
