# Generated by Django 5.0.7 on 2024-08-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_signup_gender_signup_location_signup_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(upload_to='members/')),
                ('bio', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'members_table',
            },
        ),
    ]
