# Generated by Django 5.0.7 on 2024-08-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarqueeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'marqueecontent_table',
            },
        ),
    ]
