# Generated by Django 5.0.7 on 2024-08-09 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0019_marqueecontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='image',
            new_name='story_poster',
        ),
    ]
