# Generated by Django 5.0.7 on 2024-08-09 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_rename_image_story_story_poster'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='story_poster',
            new_name='image',
        ),
    ]
