# Generated by Django 5.0.7 on 2024-08-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_rename_story_poster_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='event/'),
        ),
    ]
